config/routes.rb
Rails.application.routes.draw do

  root :to => 'logins#index'

  resources :logins do
    collection do
      post "loginuser"
    end
  end
  resources :roles
  resources :userroles
  resources :users
  resources :privileges
  resources :modulars
  resources :modularprivileges
  resources :rolemodulars

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/modular.rb
class Modular < ApplicationRecord
  has_many :modularprivileges
end

app/controllers/modulars_controller.rb
class ModularsController < ApplicationController
  before_action :set_modular, only: [:show, :edit, :update, :destroy]
  def index
    @modulars = Modular.all
  end
  def edit
    @modular = Modular.find(params[:id])
  end

  def new
    @modular = Modular.new
  end

  def create
    @modular = Modular.new(modular_params)
    respond_to do |format|
      if @modular.save
        format.html { redirect_to modulars_path, notice: '保存成功。' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @modular.update(modular_params)
        format.html { redirect_to modulars_path, notice: '保存成功。' }
        format.json { render :index, status: :ok, location: @privilege }
      else
        format.html { render :edit }
        format.json { render json: @privilege.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @modular.destroy
    respond_to do |format|
      format.html { redirect_to modulars_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_modular
    @modular = Modular.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def modular_params
    params.require(:modular).permit(:name, :displyname)
  end
end

app/helpers/modulars_helper.rb
module ModularsHelper
end

app/views/modulars/_form.html.erb
<%= form_for(@modular) do |f| %>
    <div >
      <label >名称：</label>
      <div >
        <%= f.text_field :name%>
      </div>
    </div>
    <div >
      <label >显示简称：</label>
      <div >
        <%= f.text_field :displyname%>
      </div>
    </div>
    <div >
      <label ></label>
      <div >
        <%= f.submit '确定' %>&nbsp;<%= link_to "返回",modulars_path %>
      </div>
    </div>
<% end %>

app/views/modulars/edit.html.erb
<div >
  <h3>编辑单位</h3>
</div>
<%= render 'form'%>

app/views/modulars/index.html.erb
<table>
  <thead>
    <tr>
      <th>名称</th>
      <th>显示名称</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>
  <tbody>
  <% @modulars.each do |mod| %>
      <tr>
        <td><%= mod.name %></td>
        <td><%= mod.displyname %></td>
        <td>
          <%= link_to '编辑',edit_modular_path(mod) %>
          <%= link_to '删除', mod, method: :delete, data: { confirm: '确认删除?' } %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "新增",new_modular_path%>
<%=render 'toolbar' %>

app/views/modulars/new.html.erb
<div >
  <h3>编辑单位</h3>
</div>
<%= render 'form'%>