config/routes.rb
Rails.application.routes.draw do

  root :to => 'logins#index'

  resources :logins do
    collection do
      post "loginuser"
    end
  end
  resources :roles
  resources :userroles
  resources :users
  resources :privileges
  resources :modulars
  resources :modularprivileges
  resources :rolemodulars

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_one :userpwd
  has_many :userroles
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.where("id in (select user_id from userroles where role_id in (?)) or id not in (select user_id from userroles where user_id is not null)",get_role_id)
  end
  def edit
    @user = User.find(params[:id])
    @userroles = @user.userroles.all
    @role = Role.where(get_role_sql)
  end

  def new
    @user = User.new
    @userroles = Userrole.where("1=2")
  end


  def create
    if params[:user][:pwd] == params[:user][:pwd_conf]
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          pwd=Userpwd.new(:user_id => @user.id)
          pwd.password = params[:user][:pwd]
          pwd.errpwd = 0
          pwd.nids = 0
          pwd.uptime =Time.new
          pwd.save
          format.html { redirect_to users_path, notice: '保存成功。' }
        else
          format.html { render :new }
        end
      end
    else
      @user = User.new(user_params)
      render :new
    end
  end

  def update
    if params[:user][:pwd] == params[:user][:pwd_conf]
      respond_to do |format|
        if @user.update(user_params)
          userroles = params[:user][:userrole]
          if userroles != nil
            userroles.each do |userrole|
              ur = Userrole.find(userrole)
              if userroles[userrole][:role_id] == "0"
                ur.role_id = nil
              else
                ur.role_id = userroles[userrole][:role_id]
              end
              ur.save(validate: false)
            end
          end
          pwd=@user.userpwd
          pwd.password = params[:user][:pwd]
          pwd.errpwd = params[:errus]
          pwd.nids = params[:nids]
          pwd.uptime =Time.new
          pwd.save
          format.html { redirect_to users_path, notice: '保存成功。' }
          format.json { render :index, status: :ok, location: @role }
        else
          format.html { render :edit }
          format.json { render json: @role.errors, status: :unprocessable_entity }
        end
      end
    else
      render :edit
    end
  end

  def destroy
    pwd=@user.userpwd
    if pwd != nil
      pwd.destroy
    end
    @user.userroles.each do |userrole|
      userrole.destroy
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  def show

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :nickname, :sttype, :session_id)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <div >
      <label >昵称：</label>
      <div >
        <%= f.text_field :nickname%>
      </div>
    </div>
    <div >
      <label >账号：</label>
      <div >
        <%= f.text_field :username%>
      </div>
    </div>
    <div >
      <label >密码：</label>
      <div >
        <%= f.password_field :pwd %>
      </div>
    </div>
    <div >
      <label >再输入一次密码：</label>
      <div >
        <%= f.password_field :pwd_conf %>
      </div>
    </div>
    <div >
      <label >启用：</label>
      <div >
        <%= f.check_box :sttype%>
      </div>
    </div>
    <div >
      <label >多重登录：</label>
      <div >
        <%= f.check_box :logtype%>
      </div>
    </div>
    <%if @user.id != nil%>
        <div >
          <label >密码错误次数：</label>
          <div >
            <%= text_field_tag :errus, @user.userpwd.errpwd%>
          </div>
        </div>
        <div >
          <label >密码错误次数：</label>
          <div>
            <%= text_field_tag :nids, @user.userpwd.nids%>
          </div>
        </div>
    <%end%>

    <%if @user.id != nil%>
        <table>
          <thead>
          <tr>
            <th >用户名</th>
            <th >角色</th>
            <th colspan="2">操作</th>
          </tr>
          </thead>
          <tbody>
          <% @userroles.each do |cont| %>
              <%= f.fields_for cont, index: cont.id do |cont_form|%>
                  <tr>
                    <td><%=cont.user.nickname%></td>
                    <td>
                      <% cont_form.select :role_id,options_for_select(@role.map{ |u| [u.name, u.id] } ,cont.role_id) %>
                      <%= cont_form.select(:role_id) do %>
                          <%= content_tag(:option, "  ", value: 0) %>
                          <% @role.each do |u| %>
                              <%if u.id == cont.role_id%>
                                  <%= content_tag(:option, u.name, value: u.id,selected:"selected") %>
                              <%else%>
                                <%= content_tag(:option, u.name, value: u.id) %>
                              <%end%>
                          <% end %>
                      <% end %>
                    </td>
                    <td><%= link_to '删除', userrole_path(cont, :type => 1), method: :delete, data: { confirm: '确认删除?' } %></td>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
        </table>
        <div >
          <label ></label>
          <div >
            <%= f.submit '确定' %>&nbsp;<%= link_to "返回",users_path %> <%= link_to "新增",new_userrole_path(:id => @user.id) %>
          </div>
        </div>
    <% else %>
        <div >
          <label ></label>
          <div >
            <%= f.submit '确定' %>&nbsp;<%= link_to "返回",users_path %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<div >
  <h3>编辑用户</h3>
</div>
<%= render 'form'%>

app/views/users/index.html.erb
<table >
  <thead>
    <tr>
      <th >昵称</th>
      <th >登录名</th>
      <th >状态</th>
      <th >CookieStore</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= user.username %></td>
        <td>
          <%if user.sttype == 1%>
          启用
          <%else%>
          停用
          <%end%>
        </td>
        <td><%=user.session_id%></td>
        <td>
          <%= link_to '编辑',edit_user_path(user) %>
          <%= link_to '删除', user, method: :delete, data: { confirm: '确认删除?' } %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "新增",new_user_path %>
<%=render 'toolbar' %>

app/views/users/new.html.erb
<div >
  <h3>创建用户</h3>
</div>
<%= render 'form'%>