config/routes.rb
Rails.application.routes.draw do

  root :to => 'logins#index'

  resources :logins do
    collection do
      post "loginuser"
    end
  end
  resources :roles
  resources :userroles
  resources :users
  resources :privileges
  resources :modulars
  resources :modularprivileges
  resources :rolemodulars

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :userroles
  has_many :rolemodulars
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  def index
    @roles = Role.where(get_role_sql)
    #@roles = Role.all
  end

  def edit
    @users = User.where("id in (select user_id from userroles where role_id in (?)) or id not in (select user_id from userroles where user_id is not null)",get_role_id)
    @modularprivileges = Modularprivilege.where("name is not null and id in (select modularprivilege_id from rolemodulars where role_id in (?))",get_role_id)
    @role = Role.find(params[:id])
    @userroles = @role.userroles.all
    @rolemodulars = @role.rolemodulars.all
    ddr = getauthenticate_rolearr
    if (ddr[0][0] == 0) && (ddr[1][0] == 0)
      str = 0
    else
      str = ddr[1][0]
      for i in 0..(ddr[0].length - 1)
        if ddr[1][i] < str
          str = ddr[1][i]
        end
      end
    end
    @roleselect = str
    @rolearr = ddr[0][0]
  end

  def new
    @users = User.all
    @modularprivileges = Modularprivilege.where("name is not null")
    @role = Role.new
    @roleselect = Role.all
    @rolearr = ddr[0][0]
  end

  def create
    @role = Role.new(role_params)
    respond_to do |format|
      if @role.save
        format.html { redirect_to roles_path, notice: '保存成功。' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @role.update(role_params)
        userroles = params[:role][:userrole]
        if userroles != nil
          userroles.each do |userrole|
            ur = Userrole.find(userrole)
            if userroles[userrole][:user_id] == "0"
              ur.user_id = nil
            else
              ur.user_id = userroles[userrole][:user_id]
            end
            ur.save(validate: false)
          end
        end
        userroles = params[:role][:rolemodular]
        if userroles != nil
          userroles.each do |userrole|
            ur = Rolemodular.find(userrole)
            if userroles[userrole][:modularprivilege_id] == "0"
              ur.modularprivilege_id = nil
            else
              ur.modularprivilege_id = userroles[userrole][:modularprivilege_id]
            end
            ur.save(validate: false)
          end
        end
        format.html { redirect_to roles_path, notice: '保存成功。' }
        format.json { render :index, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @role.userroles.each do |userrole|
      userrole.destroy
    end
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_path, notice: '删除成功' }
      format.json { head :no_content }
    end
  end

  def show

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def role_params
    params.require(:role).permit(:name, :remark, :sttype, :up_id)#
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
    <div >
      <label >角色名：</label>
      <div >
        <%= f.text_field :name%>
      </div>
    </div>
    <div >
      <label >备注：</label>
      <div >
        <%= f.text_field :remark%>
      </div>
    </div>
    <div >
      <label >角色组：</label>
      <div >
        <%if @rolearr == 0%>
            <%= f.number_field(:sttype, in: 0..20) %>
        <%else%>
            <%= f.number_field(:sttype , readonly:'true') %>
        <%end%>
      </div>
    </div>
    <div >
      <label >角色层级：</label>
      <div >
        <%= f.number_field(:up_id, in: (@roleselect)..20) %>
      </div>
    </div>
    <%if @role.id != nil%>
        <table>
          <thead>
          <tr>
            <th >用户名</th>
            <th >角色</th>
            <th >操作</th>
          </tr>
          </thead>
          <tbody>
          <% @userroles.each do |cont| %>
              <%= f.fields_for cont, index: cont.id do |cont_form|%>
                  <tr>
                    <td>
                      <% cont_form.select :user_id,options_for_select(@users.map{ |u| [u.nickname, u.id] } ,cont.user_id) %>
                      <%= cont_form.select(:user_id) do %>
                          <%= content_tag(:option, "  ", value: 0) %>
                          <% @users.each do |u| %>
                              <%if u.id == cont.user_id%>
                                  <%= content_tag(:option, u.nickname, value: u.id,selected:"selected") %>
                              <%else%>
                                  <%= content_tag(:option, u.nickname, value: u.id) %>
                              <%end%>
                          <% end %>
                      <% end %>
                    </td>
                    <td><%=cont.role.name%></td>
                    <td><%= link_to '删除', userrole_path(cont, :type => 2), method: :delete, data: { confirm: '确认删除?' } %></td>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
        </table>
        <div >
          <label ></label>
          <div >
            <%= link_to "新增",new_userrole_path(:rid => @role.id) %>
          </div>
        </div>

        <table>
          <thead>
          <tr>
            <th >角色</th>
            <th >模块</th>
            <th >操作</th>
          </tr>
          </thead>
          <tbody>
          <% @rolemodulars.each do |cont| %>
              <%= f.fields_for cont, index: cont.id do |cont_form|%>
                  <tr>
                    <td><%=cont.role.name%></td>
                    <td>
                      <% cont_form.select :modularprivilege_id,options_for_select(@modularprivileges.map{ |u| [u.name, u.id] } ,cont.modularprivilege_id) %>
                      <%= cont_form.select(:modularprivilege_id) do %>
                          <%= content_tag(:option, "  ", value: 0) %>
                          <% @modularprivileges.each do |u| %>
                              <%if u.id == cont.modularprivilege_id%>
                                  <%= content_tag(:option, u.name, value: u.id, selected: "selected" ) %>
                              <%else%>
                                  <%= content_tag(:option, u.name, value: u.id) %>
                              <%end%>
                          <% end %>
                      <% end %>
                    </td>
                    <td><%= link_to '删除', rolemodular_path(cont), method: :delete, data: { confirm: '确认删除?' } %></td>
                  </tr>
              <% end %>
          <% end %>
          </tbody>
        </table>
        <div >
          <label ></label>
          <div >
            <%= link_to "新增",new_rolemodular_path(:rid => @role.id) %>
          </div>
        </div>
        <div >
          <label ></label>
          <div >
            <%= f.submit '确定' %>&nbsp;<%= link_to "返回",roles_path %>
          </div>
        </div>
    <% else %>
        <div >
          <label ></label>
          <div >
            <%= f.submit '确定' %>&nbsp;<%= link_to "返回",roles_path %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/roles/edit.html.erb
<div >
  <h3>编辑单位</h3>
</div>
<%= render 'form'%>

app/views/roles/index.html.erb
<table >
  <thead>
    <tr>
      <th >名称</th>
      <th >备注</th>
      <th >角色组</th>
      <th >角色层</th>
      <th >操作</th>
    </tr>
  </thead>
  <tbody>
  <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.remark %></td>
        <td>
          <%=role.sttype%>
        </td>
        <td>
          <%=role.up_id%>
        </td>
        <td>
          <%= link_to '编辑',edit_role_path(role) %>
          <%= link_to '删除', role, method: :delete, data: { confirm: '确认删除?' } %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "新增",new_role_path%>
<%=render 'toolbar' %>

app/views/roles/new.html.erb
<div >
  <h3>编辑单位</h3>
</div>
<%= render 'form'%>